spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true  # H2 ??? ?
      path: /h2-console  # ?? ?? ?? (???? /h2-console)

  jpa:
    hibernate:
      ddl-auto: update  # ?? ?? update, ?? ? ?? ?? ??
    show-sql: true      # SQL ??? ??? ??
    properties:
      hibernate:
        format_sql: true
